### ISSUE TITLE
DeckLink output not functioning in v1.11.0

### ISSUE THREAD

**Issue by bxtdvd** [hologfx/holographics-issues#27]
Holographics is unable to see our Blackmagic DeckLink 8K Pro on v1.11.0.

v1.10.0 is able to see our DeckLink card and functions properly, with full key/fill.

After updating to v1.11.0, it says "Error initializing output" when attempting to start the output and shows no output.
Deleting the output and adding it again leaves only "No data" in the dropdown for detecting device. If you hit refresh, it gives the error "f[a0b(...)] is not a function".

macOS Catalina 10.15.7 running on a Mac Mini Intel.
Blackmagic Desktop Video 12.0

Overwriting the app with v1.10.0 allows it to work again.

**Comment by florisporro** [comment]
Fixed in v1.11.2
